gText_Birch_Welcome::
	.string "¡Hi! ¡Perdón por hacerte esperar!\p"
	.string "Bienvenido al mundo POKéMON!\p"
	.string "Mi nombre es OAK.\p"
	.string "Pero todos me llaman el POETA\n"
	.string "POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "A esto le llamamos un “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Este mundo esta inmensamente habitado\n"
	.string "por estas criaturas llamadas POKéMON.\p"
	.string "Nosotros los humanos vivimos,\n"
	.string "junto a ellos, ayudándonos,\l"
	.string "compartiendo un solo planeta.\p"
	.string "Otras veces luchamos con ellos\n"
	.string "o en su contra.\p"
	.string "Pero no te preocupes, no pasa seguido.\n"
	.string "A pesar de todo eso, no sabemos.\p"
	.string "todo sobre los POKéMON.\n"
	.string "Aun existen muchos secretos.\p"
	.string "y misterios por debelar.,\n"
	.string "Yo soy un investigador científico.\l"
	.string "A eso me dedico.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "¿Tu quién eres?$"

gText_Birch_BoyOrGirl::
	.string "¿Eres un chico?\n"
	.string "¿o una chica?$"

gText_Birch_WhatsYourName::
	.string "Muy bien.\n"
	.string "¿Cuál es tu nombre?$"

gText_Birch_SoItsPlayer::
	.string "Un gusto {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "Entonces eres {PLAYER}{KUN} y vives en la\n"
	.string "Ciudad de junto.\l"
	.string "Entiendo\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Entonces, ¿estas listo?\p"
	.string "Para vivir tu primera aventura\n"
	.string "Descubrir.\p"
	.string "Avanzar por el mundo junto\n"
	.string "a tus POKéMON, Donde los anhelos,\l"
	.string "se hacen realidad!\p"
	.string "Te estaré esperando.\n"
	.string "Ven a mi laboratorio.\p"
	.string "$"
	
