	.align 2
gText_ConfirmSave::
	.string "Quieres agregar un nuevo registro?$"

gText_AlreadySavedFile::
	.string "Ya existe un registro.\n"
	.string "quieres realizar otro registro?$"

gText_SavingDontTurnOff::
	.string "REGISTRANDO…\n"
	.string "POR FAVOR TEN PACIENCIA.$"

gText_PlayerSavedGame::
	.string "{PLAYER} realizo un registro.$"

gText_DifferentSaveFile::
	.string "ESPERA!\p"
	.string "Ya existe un registro en este\n"
	.string "diario de viaje.\p"
	.string "Si realizas otro ahora, el\n"
	.string "diario, las aventuras, objetos\l"
	.string "POKéMON, se perderan.\p"
	.string "Estas completamente seguro de\n"
	.string "quieres realizar otro registro?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "REGISTRANDO…\n"
	.string "POR FAVOR TEN PACIENCIA.$"
